### ISSUE TITLE
Sign in checkbox "Remember me" is ignored, account stays logged in with unchecked checkbox

### ISSUE THREAD

**Issue by Delivator** [DaWe35/SkyID#1]

**Comment by Delivator** [comment]
Not sure if this has been deployed and updated to but it still keeps me logged in, even if I don't check the `Remember me` checkbox.

**Comment by DaWe35** [comment]
> 
> 
> Not sure if this has been deployed and updated to but it still keeps me logged in, even if I don't check the `Remember me` checkbox.

Hi!
I'm waiting for HNS sync, maybe that's why it not works. You need to re-login to have the correct cookie set.
