### ISSUE TITLE
Beautiful loading animation

### ISSUE THREAD

**Issue by DaWe35** [DaWe35/SkyID#5]
https://codepen.io/desandro/pen/PozRQRJ
https://codepen.io/cycosta/pen/MWebyex

**Comment by cloudorbush** [comment]
this one seems cool: 

https://codepen.io/golle404/pen/EKOoyW

There's a whole bunch of them here: 

https://codepen.io/topic/loader/picks

**Comment by DaWe35** [comment]
Ohh yeah!
