### ISSUE TITLE
New user registration seems to be broken

### ISSUE THREAD

**Issue by jer** [DaWe35/SkyID#54]
Hello,

I am trying to sign up at sky-id.hns.siasky.net, and I'm consistently getting an error when submitting the new user registration. I click "sign up" and copy the passphrase, type a username in and click "Sign up"

Once I click Sign up, I get a popup saying "Failed to save file, please retry." followed by one that says "Error: unable to save profile.json" and then the page just stays there with a spinner saying "Initializing profile...."

The network console in the browser shows a 405 doing an xhr post for `skyfile`, with the message "Method Not Allowed" and the js console shows the following:

```
VM2024:1 POST https://sky-id.hns.siasky.net/skynet/skyfile 405
(anonymous) @ VM2024:1
(anonymous) @ skyid.js:1
e.exports @ skyid.js:1
e.exports @ skyid.js:1
Promise.then (async)
c.request @ skyid.js:1
(anonymous) @ skyid.js:1
e.executeRequest @ skyid.js:17
(anonymous) @ skyid.js:17
(anonymous) @ skyid.js:17
(anonymous) @ skyid.js:17
(anonymous) @ skyid.js:17
r @ skyid.js:17
t.uploadFileRequest @ skyid.js:17
(anonymous) @ skyid.js:17
(anonymous) @ skyid.js:17
(anonymous) @ skyid.js:17
(anonymous) @ skyid.js:17
r @ skyid.js:17
t.setJSON @ skyid.js:17
setJSON @ skyid.js:23
setFile @ skyid.js:23
(anonymous) @ (index):384
setMnemonic @ skyid.js:23
createAccount @ (index):379
(anonymous) @ (index):359
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
skyid.js:23 Error: Request failed with status code 405
    at e.exports (skyid.js:1)
    at e.exports (skyid.js:1)
    at XMLHttpRequest.d.onreadystatechange (skyid.js:1)
```

Thanks for your help!

**Comment by DaWe35** [comment]
Hello, thank you for submitting the issue!
Right now SkyID lost compatibility with siasky.net. I'm working on the fix, but you can use https://sky-id.hns.skyportal.xyz/ until.
I'm sorry :)

**Comment by itumz** [comment]
https://sky-id.hns.skyportal.xyz/ sign up error : Failed to save file please retry! unable to save profile.json too.

**Comment by DaWe35** [comment]
Hi, I fixed the issue :)
The only thing broken is profile picture upload - will fix soon
